name: Github container registery

on:
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - 'Dockerfile'

jobs:
    deploy-image:

      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v3

          - name: Login docker
            env: 
              CR_PAT: ${{ secrets.CR_PAT }}
            run: echo $CR_PAT | docker login ghcr.io -u krupesh1958 --password-stdin

          - name: Build docker image & tag it
            run: |
              docker build -t flask-hello-world-docker .
              docker tag flask-hello-world-docker ghcr.io/krupesh1958/flask_hello_world_docker:$(git rev-parse --verify HEAD)

          - name: Docker push
            run: |
              docker push ghcr.io/krupesh1958/flask_hello_world_docker:$(git rev-parse --verify HEAD)
